services:
  - type: web
    name: mi-app-viajes
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
